apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: "Security"
    containerImage: "registry.redhat.io/confidential-compute-attestation-tech-preview/trustee-rhel9-operator@sha256:de3c7ae5b75708aea57ab8f11208e7cba987bed9ef3ee40df25e40bf58c4be05"
    createdAt: "2024-06-07T10:06:06Z"
    operatorframework.io/suggested-namespace: trustee-operator-system
    operators.operatorframework.io/builder: operator-sdk-v1.36.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    support: Confidential Containers Community
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
    repository: https://github.com/openshift/trustee-operator
  name: trustee-operator.v0.3.0
  namespace: placeholder
  labels:
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.s390x: supported
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KbsConfig is the Schema for the kbsconfigs API
      displayName: Kbs Config
      kind: KbsConfig
      name: kbsconfigs.confidentialcontainers.org
      version: v1alpha1
  description: Remote attestation operator for confidential containers
  displayName: Red Hat build of Trustee
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0idXVpZC1mMGExYTMxYi0yZDcyLTQwNDYtODVjYS02ZWNkMDE4MTk2MDkiIGRhdGEtbmFtZT0iSWNvbnMiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDM4IDM4Ij4KICA8dGl0bGU+UmVkIEhhdCBidWlsZCBvZiBUcnVzdGVlIGljb248L3RpdGxlPgo8bWV0YWRhdGE+PD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOC4wLWMwMDEgMS4wMDAwMDAsIDAwMDAvMDAvMDAtMDA6MDA6MDAgICAgICAgICI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgICAgICAgICB4bWxuczp4bXBSaWdodHM9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9yaWdodHMvIj4KICAgICAgICAgPHhtcDpicmFuZC1jb250ZW50LXN1YnR5cGU+VGVjaG5vbG9neSBpY29uPC94bXA6YnJhbmQtY29udGVudC1zdWJ0eXBlPgogICAgICAgICA8eG1wOnJoY2MtcmlnaHRzLXJlc3RyaWN0ZWQ+bm88L3htcDpyaGNjLXJpZ2h0cy1yZXN0cmljdGVkPgogICAgICAgICA8eG1wOmJyYW5kLWxvZ28tY29sb3I+U3RhbmRhcmQ8L3htcDpicmFuZC1sb2dvLWNvbG9yPgogICAgICAgICA8eG1wOmJyYW5kLWNvbnRlbnQtdHlwZT5JY29uPC94bXA6YnJhbmQtY29udGVudC10eXBlPgogICAgICAgICA8eG1wOnJoY2MtZmlsZS1sYXN0LW1vZGlmaWVkPjIwMjUtMDItMThUMTk6MDI6MzIuOTc3WjwveG1wOnJoY2MtZmlsZS1sYXN0LW1vZGlmaWVkPgogICAgICAgICA8eG1wOnJoY2MtcHJvZHVjdD4KICAgICAgICAgICAgPHJkZjpCYWc+CiAgICAgICAgICAgICAgIDxyZGY6bGk+cmhjYy1wcm9kdWN0OnJlZC1oYXQtb3BlbnNoaWZ0PC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRmOkJhZz4KICAgICAgICAgPC94bXA6cmhjYy1wcm9kdWN0PgogICAgICAgICA8ZGM6Zm9ybWF0PmltYWdlL3N2Zyt4bWw8L2RjOmZvcm1hdD4KICAgICAgICAgPGRjOm1vZGlmaWVkPjIwMjUtMDItMThUMTk6MDQ6MDkuMzQ2WjwvZGM6bW9kaWZpZWQ+CiAgICAgICAgIDxkYzp0aXRsZT4KICAgICAgICAgICAgPHJkZjpBbHQ+CiAgICAgICAgICAgICAgIDxyZGY6bGkgeG1sOmxhbmc9IngtZGVmYXVsdCI+UmVkIEhhdCBidWlsZCBvZiBUcnVzdGVlIGljb248L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6QWx0PgogICAgICAgICA8L2RjOnRpdGxlPgogICAgICAgICA8eG1wUmlnaHRzOlVzYWdlVGVybXM+CiAgICAgICAgICAgIDxyZGY6QWx0PgogICAgICAgICAgICAgICA8cmRmOmxpIHhtbDpsYW5nPSJ4LWRlZmF1bHQiPlVzZSB0ZWNobm9sb2d5IGljb25zIHRvIHJlcHJlc2VudCBSZWQgSGF0IHByb2R1Y3RzIGFuZCBjb21wb25lbnRzLiBEbyBub3QgcmVtb3ZlIHRoZSBpY29uIGZyb20gdGhlIGJvdW5kaW5nIHNoYXBlLjwvcmRmOmxpPgogICAgICAgICAgICA8L3JkZjpBbHQ+CiAgICAgICAgIDwveG1wUmlnaHRzOlVzYWdlVGVybXM+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9InciPz48L21ldGFkYXRhPgo8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLnV1aWQtZWU5OThhMmEtMWZlYi00NTEyLTljODMtZjI1ZGM4NTNmNDdkIHsKICAgICAgICBmaWxsOiAjZTBlMGUwOwogICAgICB9CgogICAgICAudXVpZC1lNDBiNzljMC01MjVjLTQxOWEtYjkwMy02MDdmYjU1ZjY2NWEgewogICAgICAgIGZpbGw6ICNmZmY7CiAgICAgIH0KCiAgICAgIC51dWlkLWY0YmMzMDdiLTYyYmQtNDMwNC04OGI3LTEwYTViMzJmZDczMCB7CiAgICAgICAgZmlsbDogI2UwMDsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2RlZnM+CiAgPGc+CiAgICA8cmVjdCBjbGFzcz0idXVpZC1lNDBiNzljMC01MjVjLTQxOWEtYjkwMy02MDdmYjU1ZjY2NWEiIHg9IjEuNjI1IiB5PSIxLjYyNSIgd2lkdGg9IjM0Ljc1IiBoZWlnaHQ9IjM0Ljc1IiByeD0iOC4zNzUiIHJ5PSI4LjM3NSIvPgogICAgPHBhdGggY2xhc3M9InV1aWQtZWU5OThhMmEtMWZlYi00NTEyLTljODMtZjI1ZGM4NTNmNDdkIiBkPSJNMjgsMi4yNWM0LjI3MzMsMCw3Ljc1LDMuNDc2Niw3Ljc1LDcuNzV2MThjMCw0LjI3MzQtMy40NzY3LDcuNzUtNy43NSw3Ljc1SDEwYy00LjI3MzMsMC03Ljc1LTMuNDc2Ni03Ljc1LTcuNzVWMTBjMC00LjI3MzQsMy40NzY3LTcuNzUsNy43NS03Ljc1aDE4TTI4LDFIMTBDNS4wMjk0LDEsMSw1LjAyOTQsMSwxMHYxOGMwLDQuOTcwNiw0LjAyOTQsOSw5LDloMThjNC45NzA2LDAsOS00LjAyOTQsOS05VjEwYzAtNC45NzA2LTQuMDI5NC05LTktOWgwWiIvPgogIDwvZz4KICA8cGF0aCBkPSJNMjUuNTI2NCwyOS42MjVjLTIuMjc0NCwwLTQuMTI1LTEuODUwNi00LjEyNS00LjEyNXYtNC4wMjg4YzAtLjI5NDkuMjA2NS0uNTQ5OC40OTUxLS42MTEzbDMuNS0uNzQ0MWMuMDg1OS0uMDE4Ni4xNzM4LS4wMTg2LjI1OTgsMGwzLjUuNzQ0MWMuMjg4Ni4wNjE1LjQ5NTEuMzE2NC40OTUxLjYxMTN2NC4wMjg4YzAsMi4yNzQ0LTEuODUwNiw0LjEyNS00LjEyNSw0LjEyNVpNMjIuNjUxNCwyMS45NzcxdjMuNTIyOWMwLDEuNTg1NCwxLjI4OTYsMi44NzUsMi44NzUsMi44NzVzMi44NzUtMS4yODk2LDIuODc1LTIuODc1di0zLjUyMjlsLTIuODc1LS42MTA4LTIuODc1LjYxMDhaIi8+CiAgPHBhdGggY2xhc3M9InV1aWQtZjRiYzMwN2ItNjJiZC00MzA0LTg4YjctMTBhNWIzMmZkNzMwIiBkPSJNMTcuNSwyOS42MjVjLS4xMDk0LDAtLjIxOTItLjAyODgtLjMxNjktLjA4NjRsLTguNS01Yy0uMTkwOS0uMTEyMy0uMzA4MS0uMzE2OS0uMzA4MS0uNTM4NnYtMTBjMC0uMjIxNy4xMTcyLS40MjYzLjMwODEtLjUzODZsOC41LTVjLjE5NTMtLjExNTIuNDM4NS0uMTE1Mi42MzM4LDBsOC41LDVjLjE5MDkuMTEyMy4zMDgxLjMxNjkuMzA4MS41Mzg2djRjMCwuMzQ1Mi0uMjc5OC42MjUtLjYyNS42MjVzLS42MjUtLjI3OTgtLjYyNS0uNjI1di0zLjY0MjZsLTcuODc1LTQuNjMyMy03Ljg3NSw0LjYzMjN2OS4yODUybDcuODc1LDQuNjMyMywxLjU3MTgtLjkyNDhjLjI5NjQtLjE3NDMuNjgwNy0uMDc2Ny44NTU1LjIyMTcuMTc1My4yOTc0LjA3NTcuNjgwNy0uMjIxNy44NTU1bC0xLjg4ODcsMS4xMTEzYy0uMDk3Ny4wNTc2LS4yMDc1LjA4NjQtLjMxNjkuMDg2NFoiLz4KICA8cGF0aCBjbGFzcz0idXVpZC1mNGJjMzA3Yi02MmJkLTQzMDQtODhiNy0xMGE1YjMyZmQ3MzAiIGQ9Ik0yNSwyNi42MjVjLS4xNjAyLDAtLjMxOTgtLjA2MS0uNDQxOS0uMTgzMWwtMS0xYy0uMjQ0MS0uMjQ0MS0uMjQ0MS0uNjM5NiwwLS44ODM4cy42Mzk2LS4yNDQxLjg4MzgsMGwuNTU4MS41NTgxLDEuNTU4MS0xLjU1ODFjLjI0NDEtLjI0NDEuNjM5Ni0uMjQ0MS44ODM4LDBzLjI0NDEuNjM5NiwwLC44ODM4bC0yLDJjLS4xMjIxLjEyMjEtLjI4MTcuMTgzMS0uNDQxOS4xODMxWiIvPgogIDxwYXRoIGQ9Ik0xOS4yMjYxLDE2Ljg1NDVjMC0uOTUxMi0uNzczOS0xLjcyNDYtMS43MjUxLTEuNzI0NnMtMS43MjQ2Ljc3MzQtMS43MjQ2LDEuNzI0NmMwLC42ODU1LjQwNDgsMS4yNzM5Ljk4NTIsMS41NTE5bC0uOTc3OCwzLjkxMjljLS4wMTg2LjA3NDctLjAwMi4xNTM4LjA0NTQuMjE0NHMuMTIwMS4wOTYyLjE5NzMuMDk2MmgyLjk0OTdjLjA3NzEsMCwuMTQ5OS0uMDM1Ni4xOTczLS4wOTYycy4wNjQtLjEzOTYuMDQ1NC0uMjE0NGwtLjk3ODMtMy45MTI4Yy41ODA2LS4yNzguOTg1Ny0uODY2NS45ODU3LTEuNTUyWiIvPgo8L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - confidentialcontainers.org
          resources:
          - kbsconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - confidentialcontainers.org
          resources:
          - kbsconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - confidentialcontainers.org
          resources:
          - kbsconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: trustee-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: trustee-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: trustee-operator
          control-plane: controller-manager
        name: trustee-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: KBS_IMAGE_NAME
                  value: "registry.redhat.io/confidential-compute-attestation-tech-preview/trustee-rhel9@sha256:de8b54e65e3d1d1a3973e34194e2449cec8d53054f2285cc3b1fa92022f0a7f8"
                - name: AS_IMAGE_NAME
                  value: ghcr.io/confidential-containers/staged-images/coco-as-grpc:latest
                - name: RVPS_IMAGE_NAME
                  value: ghcr.io/confidential-containers/staged-images/rvps:latest
                image: "registry.redhat.io/confidential-compute-attestation-tech-preview/trustee-rhel9-operator@sha256:de3c7ae5b75708aea57ab8f11208e7cba987bed9ef3ee40df25e40bf58c4be05"
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: trustee-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: trustee-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - trustee
  - Confidential Computing
  - Attestation
  links:
  - name: Red Hat build of Trustee
    url: https://github.com/openshift/trustee-operator
  maintainers:
  - email: support@redhat.com
    name: Red Hat
  maturity: beta
  provider:
    name: Red Hat
    url: https://github.com/confidential-containers
  replaces: trustee-operator.v0.2.0
  version: 0.3.0
