apiVersion: v1
kind: ConfigMap
metadata:
  name: ita-kbs-config-grpc
  namespace: trustee-operator-system
data:
  kbs-config.toml: |
    [http_server]
    sockets = ["0.0.0.0:8080"]
    insecure_http = true

    [admin]
    insecure_api = true
    auth_public_key = "/etc/auth-secret/kbs.pem"

    [attestation_token]
    trusted_jwk_sets = ["https://portal.trustauthority.intel.com"]

    [attestation_service]
    type = "intel_ta"
    base_url = "https://api.trustauthority.intel.com"
    api_key = "tBfd5kKX2x9ahbodKV1..."
    certs_file = "https://portal.trustauthority.intel.com"
    allow_unmatched_policy = true

    [[plugins]]
    name = "resource"
    type = "LocalFs"
    dir_path = "/opt/confidential-containers/kbs/repository"

    [policy_engine]
    policy_path = "/opt/confidential-containers/opa/policy.rego"
