apiVersion: v1
data:
  sgx_default_qcnl.conf: |
    {
      "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/"
    }
kind: ConfigMap
metadata:
  name: tdx-config
  namespace: trustee-operator-system
