apiVersion: v1
kind: ConfigMap
metadata:
  name: tdx-ita-config
  namespace: trustee-operator-system
data:
  kbs-config.toml: |
    [http_server]
    sockets = ["0.0.0.0:8080"]
    insecure_http = true
    payload_request_size = 2
    
    [admin]
    auth_public_key = "/etc/auth-secret/publicKey"
    insecure_api = false
    
    [attestation_token]
    trusted_jwk_sets = ["https://portal.trustauthority.intel.com"]
    extra_teekey_paths = ["/tdx/attester_runtime_data/tee-pubkey"]
    
    [attestation_service]
    type = "intel_ta"
    base_url = "https://api.trustauthority.intel.com"
    api_key = "tBfd5kKX2x9ahbodKV1..."
    certs_file = "https://portal.trustauthority.intel.com"
    
    [attestation_service.rvps_config]
    type = "BuiltIn"
    
    [attestation_service.rvps_config.storage]
    type = "LocalJson"
    file_path = "/opt/confidential-containers/rvps/reference-values/reference-values.json"
    
    [policy_engine]
    policy_path = "/opt/confidential-containers/opa/policy.rego"
    
    [[plugins]]
    name = "resource"
    type = "LocalFs"
    dir_path = "/opt/confidential-containers/kbs/repository"