apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && files.all.exists(path, !path.matches('bundle*|tests/*|.tekton/*bundle*'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee
    appstudio.openshift.io/component: trustee-operator
    pipelines.appstudio.openshift.io/type: build
  name: trustee-operator-on-pull-request
  namespace: ose-osc-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee/trustee-operator:on-pr-{{revision}}
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "."}, {"type": "rpm", "path": "rpm"}]'
  - name: hermetic
    value: "true"
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  pipelineRef:
    name: docker-build-multi-platform-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-trustee-operator
  timeouts:
    pipeline: 2h0m0s
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
