#!/bin/bash

# Collect trustee-related CRDs
BASE_COLLECTION_PATH="/must-gather"
mkdir -p "${BASE_COLLECTION_PATH}/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/"

# Collect KbsConfig and TrusteeConfig CRDs
/usr/bin/oc get crd kbsconfigs.confidentialcontainers.org -o yaml > "${BASE_COLLECTION_PATH}/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/kbsconfigs.confidentialcontainers.org.yaml" 2>/dev/null
/usr/bin/oc get crd trusteeconfigs.confidentialcontainers.org -o yaml > "${BASE_COLLECTION_PATH}/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/trusteeconfigs.confidentialcontainers.org.yaml" 2>/dev/null

exit 0
