#!/bin/bash

# Resource list
resources=()

# Trustee operator related namespaces
resources+=(ns/trustee-operator-system)
resources+=(ns/openshift-operator-lifecycle-manager)
resources+=(ns/openshift-marketplace)

# Nodes and Machines (for troubleshooting deployment issues)
resources+=(nodes)
resources+=(machines)

# Run the collection of resources using must-gather
for resource in "${resources[@]}"; do
    echo "Inspecting resource ${resource}..."
    /usr/bin/oc adm inspect --dest-dir must-gather --all-namespaces "${resource}" &> /dev/null
done

# Collect CRDs
/usr/bin/gather_crds

# Collect OLM installation resources
/usr/bin/gather_olm_resources

# Collect trustee operator logs and resources
/usr/bin/gather_trustee_operator

exit 0
